### ISSUE TITLE
automatic date

### ISSUE THREAD

**Issue by shiffman** [magicbookproject/magicbook#10]
In my book the title page says:

```
<p>version 2.0 alpha, generated July 13, 2016</p>
```

I would love to be able to auto-generate the date.   There is probably also something interesting in terms of auto rendering the most recent commit hash or git tag or something, but this is certainly not a high priority.

**Comment by meiamsome** [comment]
A relatively easy way of implementing this would be to allow access to environment variables from liquid - then any needed data can be generated in a prior build script

**Comment by codebanter** [comment]
I'm getting this error when trying to build. 

Config file detected: magicbook.json
{ Error: Cannot find module '/Users/.../node_modules/stylesheets' ...}

Any ideas?
