### ISSUE TITLE
Any advacement on magicbook recently?

### ISSUE THREAD

**Issue by ofenerci** [magicbookproject/magicbook#14]
Hello, 

It looks that magicbook has not been updated frequently anymore. Is magicbook project still active?

**Comment by runemadsen** [comment]
Yes, it is very much still alive. Haven't had time for development over the last 6 months, but I'm using it daily.

**Comment by ofenerci** [comment]
Very nice! I wonder we could use Asciidoc format  for magicbook (was being used in its older version [her](https://github.com/runemadsen/Magic-Book-Project)

**Comment by runemadsen** [comment]
It currently doesn't support Asciidoc (I have used Asciidoc a lot and I'm not the biggest fan), but you should be able to write a simple plugin that does asciidoc conversion. You would basically just need to make a version of the [Markdown plugin](https://github.com/magicbookproject/magicbook/blob/master/src/plugins/markdown.js) that runs the Asciidoc conversion instead.

**Comment by sergiomajluf** [comment]
Hi! what node version are you running it with? I'm having problems with the latests 6x and 8x and a "#Prince" module.

**Comment by runemadsen** [comment]
What problems are you having @sergiomajluf?

**Comment by runemadsen** [comment]
I'm waiting for a pull request in the Prince npm module, which will solve this problem. Will close this issue once it is fixed.

**Comment by runemadsen** [comment]
The `prince` module just released a fix, and I just published `0.1.13` to bump to that version. Everything should be good now.

**Comment by sergiomajluf** [comment]
Thanks Rune. [This](https://github.com/magicbookproject/magicbook/issues/15#issuecomment-327818426) solved the Prince error for me. It's working OK now
