### ISSUE TITLE
Two html/body

### ISSUE THREAD

**Issue by aratinau** [magicbookproject/magicbook#20]
Hello,
I saw a second ``` <html><head></head><body> ``` on the example build, in html example. 

```
 <div class="container">
	<html><head></head><body><section data-type="chapter" id="html-chapter-8vy0FZP">
	<h1>HTML Chapter</h1>
	<p id="second-chapter-id">This is a chapter written in HTML</p>
	</section></body></html>
</div>
```
I would like to remove this but I don't know where to start to looking for?
Maybe I'm not the only one to have this?
Thanks for your help!

**Comment by runemadsen** [comment]
Thanks @aratinau. I think this was created by an update in the html parser. I'll take a look this week and push a fix.

**Comment by runemadsen** [comment]
I just pushed version `0.1.17` to fix this. It was caused by a breaking change in the HTML parser (cheerio) that we use. Everything should be working now.

**Comment by aratinau** [comment]
Everything works now, thank you!
