### ISSUE TITLE
needs assessment wrt Nature of Code 2.0?

### ISSUE THREAD

**Issue by nopivnick** [magicbookproject/magicbook#27]
I've done some perusing as far as current digital publishing platform options but it occurs to me rather than a broad write up perhaps it would be best if there were a rudimentary needs assessment of some kind vis a vis Magic Book as it pertains to @shiffman 's Nature of Code overhaul?

what exactly are the short term, mid term, and long term requirements for Magic Book as dictated by [NOC v2.0](https://github.com/nature-of-code/noc-book-2)?

@joeyklee mentioned first and foremost is getting chapter 10 ready for the upcoming IMA course in Fall 2019 but to what extent, if any, is that dependent upon further development work on Magic Book?

there was mention of porting Nature of Code content to Markdown; ability to generate an index from Markdown; and ePub + Mobi output. roughly where do those fall in terms of timeline and priority?

is there a roadmap of some kind beyond the most recent version of [TODO.md](https://github.com/magicbookproject/magicbook/blob/9bbfcbb2607f8ff6eca01332f4b845c6162e68b4/TODO.md), now three years old?

if not, perhaps a rudimentary [Project](https://github.com/magicbookproject/magicbook/projects) board for the Magic Book repo might be a worth while exercise?

**Comment by njames** [comment]
Bump. 

I have just come across NOC and by extension the magicbookproject in the current form and in this one. 

I have tried to install the npm version but there is possibly a few more things to tweak on my system. 

I would really like to use MBP on my MBP for some publishing plans I have up my sleeve but how love is it going to get?

**Comment by shiffman** [comment]
I'm going to close this issue as a lot of progress is now finally happening for Nature of Code! 

https://github.com/nature-of-code/book-website-2nd-edition
https://nature-of-code-2nd-edition.netlify.app/
