### ISSUE TITLE
Index terms markup

### ISSUE THREAD

**Issue by shiffman** [magicbookproject/magicbook#3]
There is probably a larger discussion to have, but I've found that the ASCIIDOC to HTMLBook conversion for NOC resulted in the following:

```html
<p><a data-primary="random walks" data-type="indexterm">&nbsp;</a></p>

<p>CONTENT</p>
```

This markup leaves blank paragraphs and extra spacing in the book.  I could do a global replace like:

```html
<a data-primary="random walks" data-type="indexterm"></a>

<p>CONTENT</p>
```

But then these index terms are floating.  What is the proper markup?  Do I need them to just be moved and embedded into actual paragraphs?

```html
<p><a data-primary="random walks" data-type="indexterm"></a> CONTENT</p>
```

Is the `&nbsp;` necessary?

See: https://github.com/shiffman/The-Nature-of-Code/blob/master/chapters/00_7_intro.html#L17

**Comment by runemadsen** [comment]
Yeah, this is probably a result of the asciidoc conversion. In a perfect world, they would all look like this:

```html
<p>This is some text about tigers<a data-type="indexterm" data-primary="Tiger" />. They are very dangerous.</p>
```

But given that the indexterm simply indicates a target for the back-of-the-book index, it won't make much of a difference whether it's exactly next to the word or not. But you should probably remove the empty paragraph, as it will give extra space in your book.
