### ISSUE TITLE
Different files for different builds

### ISSUE THREAD

**Issue by shiffman** [magicbookproject/magicbook#4]
This is a small thing and might only come up rarely, but I have an HTML file that I want to include for my HTML build, but not for my PDF build.  Right now there is only one `files` array in `magicbook.json` which is separate from the `builds` array.

**Comment by runemadsen** [comment]
Hi Dan

This used to not be clear in the documentation, but each build object can have a `files` array. Take a look at the updated README: https://github.com/magicbookproject/magicbook#builds

**Comment by shiffman** [comment]
Ah, sorry, apologies for missing that, thank you!

**Comment by runemadsen** [comment]
No problemo!
