### ISSUE TITLE
Math Formula

### ISSUE THREAD

**Issue by shiffman** [magicbookproject/magicbook#5]
I've read [the section in the README](https://github.com/magicbookproject/magicbook#math) about math with latex + katex.  Just opening an issue to track the status.  Should math formula render in either PDF or HTML now or not yet?

**Comment by runemadsen** [comment]
I actually *just* finished a giant rewrite of the plugin infrastructure, and I've moved the `katex` plugin out of the core: https://github.com/magicbookproject/magicbook-katex. I also fixed a few issues around javascript compilation, which might fix your problems. However, I'm not entirely sure how Prince XML behaves with Katex. Let's take a look at this tomorrow.

**Comment by shiffman** [comment]
Great, thanks!
